apiVersion: apps/v1
kind: Deployment
metadata:
  name: xevi-linux-deployment
  namespace: xevi
  labels:
    app: xevi-linux-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: xevi-linux-app
  template:
    metadata:
      labels:
        app: xevi-linux-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: springbootrest-repository
        image: 267737644774.dkr.ecr.eu-west-1.amazonaws.com/springbootrest-repository:0.0.5
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux